package caddy

import (
	"database/sql"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/kashifsb/nurix/internal/store"
)

// SyncCaddyfile regenerates the Caddyfile from the database and reloads Caddy.
func SyncCaddyfile(db *sql.DB, caddyfilePath string) error {
	domains, grouped, err := store.GetAllGroupedByDomain(db)
	if err != nil {
		return fmt.Errorf("failed to fetch data for sync: %w", err)
	}

	var builder strings.Builder
	builder.WriteString("# Auto-generated by nurix CLI — DO NOT EDIT MANUALLY\n")

	for i, domain := range domains {
		builder.WriteString("\n")
		builder.WriteString(generateBanner(domain.Domain))
		builder.WriteString("\n")

		records, exists := grouped[domain.ID]
		if exists && len(records) > 0 {
			for _, r := range records {
				builder.WriteString(fmt.Sprintf("%s {\n", r.Owner))
				builder.WriteString(fmt.Sprintf("\treverse_proxy %s\n", r.Target))
				builder.WriteString("}\n\n")
			}
		}

		if i < len(domains)-1 {
			builder.WriteString("\n")
		}
	}

	content := builder.String()

	if err := os.WriteFile(caddyfilePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write Caddyfile at %s: %w", caddyfilePath, err)
	}

	fmt.Printf("📄 Caddyfile written to %s\n", caddyfilePath)

	if err := reloadCaddy(caddyfilePath); err != nil {
		return fmt.Errorf("caddyfile written but reload failed: %w", err)
	}

	fmt.Println("🔄 Caddy reloaded successfully")
	return nil
}

func generateBanner(domain string) string {
	upper := strings.ToUpper(domain)
	middle := fmt.Sprintf("########## %s ##########", upper)
	border := strings.Repeat("#", len(middle))

	var b strings.Builder
	b.WriteString(border + "\n")
	b.WriteString(middle + "\n")
	b.WriteString(border + "\n")
	return b.String()
}

func reloadCaddy(caddyfilePath string) error {
	cmd := exec.Command("systemctl", "reload", "caddy")
	output, err := cmd.CombinedOutput()
	if err != nil {
		cmd2 := exec.Command("caddy", "reload", "--config", caddyfilePath)
		output2, err2 := cmd2.CombinedOutput()
		if err2 != nil {
			return fmt.Errorf(
				"systemctl reload failed: %s\ncaddy reload failed: %s",
				string(output), string(output2),
			)
		}
	}
	return nil
}
